# Это GCP Cloud Build definition который вызывает GCP Cloud Deploy как последний шаг

# Складываем build-артефакты из всех кубиков в GCP Artifact Registry      
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/bondarevsky-docker/my-image:$SHORT_SHA'

# другие типы артефактов аналогично 
# https://cloud.google.com/build/docs/building/store-artifacts-in-cloud-storage
  
# Складываем build-логи в GCP Cloud Logs
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build and tag using commit sha
  - name: 'gcr.io/cloud-builders/docker'
    id: "docker build"
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/bondarevsky-docker/my-image:$SHORT_SHA', '.', '-f', 'Dockerfile']
  
# Invoke deploy via Cloud Deploy
  - id: "deploy releases"
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        "deploy", "releases", "create", "rel-$SHORT_SHA",
        "--delivery-pipeline=cloud-run-pipeline",
        "--region=us-central1",
        "--skaffold-file=deploy/skaffold.yaml",
        "--images", "image1=us-central1-docker.pkg.dev/$PROJECT_ID/bondarevsky-docker/my-image:$SHORT_SHA"
      ]

