apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-clouddeploy-cloudrun
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image:${SHORT_SHA}
