apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: my-app
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image
deploy:
  cloudrun:
    region: us-central1
    projectId: ${PROJECT_ID}
