apiVersion: skaffold/v3
kind: Config
deploy:
  cloudrun: {}
profiles:
  - name: demo-btykkrf-target-1
    manifests:
      rawYaml:
      - cloudrun-dev.yaml
  - name: prod
    manifests:
      rawYaml:
      - cloudrun-prod.yaml
