apiVersion: skaffold/v3
kind: Config
deploy:
  cloudrun: {}
profiles:
  - name: dev-profile
    manifests:
      rawYaml:
      - cloudrun-dev.yaml
  - name: qa-profile
    manifests:
      rawYaml:
      - cloudrun-qa.yaml
  - name: prod-profile
    manifests:
      rawYaml:
      - cloudrun-prod.yaml
